begin;

-- ============================================================
-- AEGRIS FIELD VALIDATIONS / GROUND TRUTH
-- 2026-09-07
--
-- Purpose:
-- Connect one immutable AEGRIS analysis with real field
-- observation supplied by an agronomist.
--
-- Important:
-- aegris_alerts can be reused/updated by newer analyses.
-- Therefore analysis_id is the authoritative validation anchor.
-- ============================================================


-- ------------------------------------------------------------
-- 1. TABLE
-- ------------------------------------------------------------

create table if not exists public.field_validations (
  id bigint generated by default as identity primary key,

  project_id bigint not null
    references public.projects(id)
    on delete cascade,

  analysis_id bigint not null
    references public.analysis(id)
    on delete cascade,

  recommendation_id bigint
    references public.aegris_recommendations(id)
    on delete set null,

  alert_id bigint
    references public.aegris_alerts(id)
    on delete set null,

  validated_by uuid not null
    references auth.users(id)
    on delete restrict,

  validation_result text not null,

  actual_cause text,

  observed_at date not null,

  note text,

  created_at timestamp with time zone
    not null
    default now(),

  updated_at timestamp with time zone
    not null
    default now(),

  constraint field_validations_validation_result_check
    check (
      validation_result in (
        'confirmed',
        'partially_confirmed',
        'not_confirmed'
      )
    ),

  constraint field_validations_actual_cause_check
    check (
      actual_cause is null
      or actual_cause in (
        'drought_water_stress',
        'nutrition',
        'disease',
        'pest',
        'crop_damage',
        'weed',
        'other',
        'no_problem'
      )
    ),

  constraint field_validations_note_length_check
    check (
      note is null
      or char_length(note) <= 5000
    ),

  constraint field_validations_analysis_user_unique
    unique (analysis_id, validated_by)
);


comment on table public.field_validations is
  'Ground-truth observations linking one immutable AEGRIS analysis to the real condition observed in the field by an agronomist.';

comment on column public.field_validations.project_id is
  'Project/field that was inspected.';

comment on column public.field_validations.analysis_id is
  'Authoritative immutable AEGRIS analysis that the agronomist is validating.';

comment on column public.field_validations.recommendation_id is
  'Recommendation produced for the validated analysis, when available.';

comment on column public.field_validations.alert_id is
  'Alert through which the validation workflow was opened. Alert rows may later point to newer analyses, therefore this is not the authoritative validation anchor.';

comment on column public.field_validations.validated_by is
  'Authenticated user who performed or entered the field validation.';

comment on column public.field_validations.validation_result is
  'confirmed, partially_confirmed, or not_confirmed.';

comment on column public.field_validations.actual_cause is
  'Observed real-world cause using a controlled AEGRIS cause vocabulary.';

comment on column public.field_validations.observed_at is
  'Date on which the field condition was observed.';

comment on column public.field_validations.note is
  'Optional agronomist note, maximum 5000 characters.';


-- ------------------------------------------------------------
-- 2. INDEXES
-- ------------------------------------------------------------

create index if not exists field_validations_project_id_idx
  on public.field_validations (project_id);

create index if not exists field_validations_analysis_id_idx
  on public.field_validations (analysis_id);

create index if not exists field_validations_recommendation_id_idx
  on public.field_validations (recommendation_id);

create index if not exists field_validations_alert_id_idx
  on public.field_validations (alert_id);

create index if not exists field_validations_validated_by_idx
  on public.field_validations (validated_by);

create index if not exists field_validations_observed_at_idx
  on public.field_validations (observed_at desc);

create index if not exists field_validations_result_idx
  on public.field_validations (validation_result);

create index if not exists field_validations_project_observed_at_idx
  on public.field_validations (
    project_id,
    observed_at desc
  );


-- ------------------------------------------------------------
-- 3. REFERENCE CONSISTENCY
--
-- FK alone only verifies that referenced rows exist.
-- This trigger also guarantees that analysis/recommendation/alert
-- belong to the same project and, where applicable, the same
-- analysis being validated.
-- ------------------------------------------------------------

create or replace function public.validate_field_validation_references()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
begin

  if not exists (
    select 1
    from public.analysis a
    where a.id = new.analysis_id
      and a.project_id = new.project_id
  ) then
    raise exception
      'analysis_id % does not belong to project_id %',
      new.analysis_id,
      new.project_id;
  end if;


  if new.recommendation_id is not null
     and not exists (
       select 1
       from public.aegris_recommendations r
       where r.id = new.recommendation_id
         and r.project_id = new.project_id
         and (
           r.analysis_id is null
           or r.analysis_id = new.analysis_id
         )
     ) then
    raise exception
      'recommendation_id % is inconsistent with project_id % or analysis_id %',
      new.recommendation_id,
      new.project_id,
      new.analysis_id;
  end if;


  if new.alert_id is not null
     and not exists (
       select 1
       from public.aegris_alerts al
       where al.id = new.alert_id
         and al.project_id = new.project_id
     ) then
    raise exception
      'alert_id % does not belong to project_id %',
      new.alert_id,
      new.project_id;
  end if;


  return new;
end;
$function$;


drop trigger if exists field_validations_reference_consistency
  on public.field_validations;

create trigger field_validations_reference_consistency
before insert or update
on public.field_validations
for each row
execute function public.validate_field_validation_references();


-- ------------------------------------------------------------
-- 4. UPDATED_AT
-- ------------------------------------------------------------

create or replace function public.set_field_validation_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;


drop trigger if exists field_validations_set_updated_at
  on public.field_validations;

create trigger field_validations_set_updated_at
before update
on public.field_validations
for each row
execute function public.set_field_validation_updated_at();


-- ------------------------------------------------------------
-- 5. ROW LEVEL SECURITY
-- ------------------------------------------------------------

alter table public.field_validations
  enable row level security;


-- ------------------------------------------------------------
-- SELECT
--
-- User can see validations when:
-- 1) project belongs directly to them, OR
-- 2) they are a member of the project's organization.
-- ------------------------------------------------------------

drop policy if exists field_validations_select
  on public.field_validations;

create policy field_validations_select
on public.field_validations
for select
to authenticated
using (
  exists (
    select 1
    from public.projects p
    where p.id = field_validations.project_id
      and (
        p.user_id = auth.uid()

        or exists (
          select 1
          from public.organization_members om
          where om.organization_id = p.organization_id
            and om.user_id = auth.uid()
        )
      )
  )
);


-- ------------------------------------------------------------
-- INSERT
--
-- Direct project owner can validate.
--
-- Organization users can validate only when their role is:
-- owner / admin / member.
--
-- viewer is intentionally read-only.
--
-- validated_by must always equal the current authenticated user.
-- ------------------------------------------------------------

drop policy if exists field_validations_insert
  on public.field_validations;

create policy field_validations_insert
on public.field_validations
for insert
to authenticated
with check (
  validated_by = auth.uid()

  and exists (
    select 1
    from public.projects p
    where p.id = field_validations.project_id
      and (
        p.user_id = auth.uid()

        or exists (
          select 1
          from public.organization_members om
          where om.organization_id = p.organization_id
            and om.user_id = auth.uid()
            and om.role in (
              'owner',
              'admin',
              'member'
            )
        )
      )
  )
);


-- ------------------------------------------------------------
-- UPDATE
--
-- User may edit only their own validation.
-- They must still have write access to the project.
-- ------------------------------------------------------------

drop policy if exists field_validations_update
  on public.field_validations;

create policy field_validations_update
on public.field_validations
for update
to authenticated
using (
  validated_by = auth.uid()

  and exists (
    select 1
    from public.projects p
    where p.id = field_validations.project_id
      and (
        p.user_id = auth.uid()

        or exists (
          select 1
          from public.organization_members om
          where om.organization_id = p.organization_id
            and om.user_id = auth.uid()
            and om.role in (
              'owner',
              'admin',
              'member'
            )
        )
      )
  )
)
with check (
  validated_by = auth.uid()

  and exists (
    select 1
    from public.projects p
    where p.id = field_validations.project_id
      and (
        p.user_id = auth.uid()

        or exists (
          select 1
          from public.organization_members om
          where om.organization_id = p.organization_id
            and om.user_id = auth.uid()
            and om.role in (
              'owner',
              'admin',
              'member'
            )
        )
      )
  )
);


-- ------------------------------------------------------------
-- 6. PRIVILEGES
--
-- No DELETE grant intentionally.
-- Field-validation records form an audit/validation dataset.
-- Corrections are made through UPDATE.
-- ------------------------------------------------------------

revoke all
on table public.field_validations
from anon;

revoke all
on table public.field_validations
from authenticated;

grant select, insert, update
on table public.field_validations
to authenticated;


revoke all
on sequence public.field_validations_id_seq
from anon;

grant usage, select
on sequence public.field_validations_id_seq
to authenticated;


-- Trigger helper functions are not public APIs.

revoke all
on function public.validate_field_validation_references()
from public, anon, authenticated;

revoke all
on function public.set_field_validation_updated_at()
from public, anon, authenticated;


commit;