begin;

create table if not exists public.support_tickets (
  id bigint generated by default as identity primary key,

  user_id uuid null references auth.users(id) on delete set null,

  email text not null,
  subject text not null,
  message text not null,

  status text not null default 'open'
    check (status in ('open', 'in_progress', 'resolved', 'closed')),

  priority text not null default 'normal'
    check (priority in ('low', 'normal', 'high', 'urgent')),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz null
);

create index if not exists support_tickets_user_id_idx
  on public.support_tickets(user_id);

create index if not exists support_tickets_status_idx
  on public.support_tickets(status);

create index if not exists support_tickets_created_at_idx
  on public.support_tickets(created_at desc);

commit;