@'
begin;

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null,
  action text not null,
  target_type text not null,
  target_id text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_log_created_at_idx
  on public.admin_audit_log (created_at desc);

create index if not exists admin_audit_log_admin_user_id_idx
  on public.admin_audit_log (admin_user_id);

create index if not exists admin_audit_log_target_idx
  on public.admin_audit_log (target_type, target_id);

alter table public.admin_audit_log enable row level security;

drop policy if exists "service_role_full_access_admin_audit_log"
on public.admin_audit_log;

create policy "service_role_full_access_admin_audit_log"
on public.admin_audit_log
for all
to service_role
using (true)
with check (true);

grant select, insert
on table public.admin_audit_log
to service_role;

grant usage, select
on sequence public.admin_audit_log_id_seq
to service_role;

commit;
'@ | Set-Content -LiteralPath ".\supabase\migrations\20260829_admin_audit_log.sql" -Encoding utf8